### ISSUE TITLE
Migrating to Pydantic v2

### ISSUE THREAD

**Issue by bennyw31210** [jacobszpz/BlackboardSync#85]
When I run the 'blackboard_sync' module using 'python -m blackboard_sync', the following error occurs:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\blackboard_sync\__main__.py", line 32, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "C:\Python311\Lib\site-packages\blackboard_sync\__main__.py", line 27, in main
    BBSyncController()
  File "C:\Python311\Lib\site-packages\blackboard_sync\sync_controller.py", line 58, in __init__
    self._build_login_window(self.model.university.login)
  File "C:\Python311\Lib\site-packages\blackboard_sync\sync_controller.py", line 96, in _build_login_window
    self.login_window = LoginWebView(start_url=uni_login_info.start_url,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\blackboard_sync\qt\qt_elements.py", line 475, in __init__
    self._init_ui()
  File "C:\Python311\Lib\site-packages\blackboard_sync\qt\qt_elements.py", line 480, in _init_ui
    self.web_view.load(QUrl.fromUserInput(self.start_url))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  fromUserInput(userInput: str): argument 1 has unexpected type 'pydantic_core._pydantic_core.Url'
  fromUserInput(userInput: str, workingDirectory: str, options: Union[QUrl.UserInputResolutionOptions, QUrl.UserInputResolutionOption] = QUrl.DefaultResolution): argument 1 has unexpected type 'pydantic_core._pydantic_core.Url'

**Comment by jacobszpz** [comment]
It probably got undetected after merging #65 since I forgot to re-run pipenv install, but it should be fixed in newly-available release 0.9.9. Bumping pydantic also means that I should fix this warning sooner or later:
```
.../lib/python3.11/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_mutation' has been removed
```

Please let me know if you run into any other issues

**Comment by jacobszpz** [comment]
This is the breaking change in pydantic v2:

```
Url and Dsn types in pydantic.networks no longer inherit from str¶

In Pydantic V1 the AnyUrl type inherited from str, and all the other Url and Dsn types inherited from these. In Pydantic V2 these types are built on two new Url and MultiHostUrl classes using Annotated.

Inheriting from str had upsides and downsides, and for V2 we decided it would be better to remove this. To use these types in APIs which expect str you'll now need to convert them (with str(url)).
```

**Comment by jacobszpz** [comment]
Release 0.9.11 should fix another minor bug where some content would be skipped due to a pydantic validation error.

**Comment by jacobszpz** [comment]
@bennyw31210 Since you are one of the early adopters, I would like to know how you have been finding the app, if you still use it, and what university you are using it with.
